{% set name = "stackstac" %}
{% set version = "0.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/stackstac-{{ version }}.tar.gz
  sha256: 1af0e1251100fe506b1f3c035ffcc34111ad67b264275d14a6775c4991e5f7f6

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - pdm-pep517
  run:
    - numpy <3,>1.23
    - pandas <3,>=2
    - python >={{ python_min }},<4.0
    - dask-core >=2022.1.1
    - pyproj <4.0.0,>=3.0.0
    - rasterio <2.0.0,>=1.3.0
    - xarray >=0.18

test:
  imports:
    - stackstac
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://stackstac.readthedocs.io/en/latest/index.html
  summary: Load a STAC collection into xarray with dask
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - TomAugspurger
    - gjoseph92
    - scottyhq
    - ocefpaf
    - raybellwaves
