{% set name = "stackstac" %}
{% set version = "0.4.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/stackstac-{{ version }}.tar.gz
  sha256: 2a4137f590ab005e709078da199d666d2e357811abb8ea508c1e9d3b876cd76f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8,<4.0

    - dask-core >=2022.1.1,<2023.0.0
    - pyproj >=3.0.0,<4.0.0
    - rasterio >=1.3.0,<2.0.0
    - xarray >=0.18
    # - ipywidgets >=7.6.3,<8.0.0
    # - numpy >=1.20.0,<2.0.0
    # - scipy >=1.6.1,<2.0.0

test:
  imports:
    - stackstac
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://stackstac.readthedocs.io/en/latest/index.html
  summary: Load a STAC collection into xarray with dask
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - TomAugspurger
    - gjoseph92
    - scottyhq
    - ocefpaf
    - raybellwaves
