{% set name = "stackstac" %}
{% set version = "0.4.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/stackstac-{{ version }}.tar.gz
  sha256: be3e9780b20b5027cdab06e25f24e1614e6d10d09c9506bb78567e8d28d77e35

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8,<4.0
    - pip
    - pdm-pep517
  run:
    - python >=3.8,<4.0
    - dask-core >=2022.1.1
    - pyproj >=3.0.0,<4.0.0
    - rasterio >=1.3.0,<2.0.0
    - xarray >=0.18

test:
  imports:
    - stackstac
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://stackstac.readthedocs.io/en/latest/index.html
  summary: Load a STAC collection into xarray with dask
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - TomAugspurger
    - gjoseph92
    - scottyhq
    - ocefpaf
    - raybellwaves
